#!/usr/bin/perl -w
use strict;
use lib "/opt/rt4/lib";
use lib "/opt/rt4/etc";
use RT::Interface::CLI qw(Init);

no warnings 'once';

Init();
print $RT::Handle->SimpleQuery("select nextval('tickets_id_seq')")->fetchall_arrayref->[0][0];
print $/;
