#!/usr/bin/perl -w
use strict;
use lib "/usr/share/request-tracker4/lib";
use lib "/etc/request-tracker4";
use RT::Interface::CLI qw(Init);

no warnings 'once';

Init();
print $RT::Handle->SimpleQuery("select nextval('tickets_id_seq')")->fetchall_arrayref->[0][0];
print $/;
