#!/bin/sh
domail=nil
taglist="trunk:krb5-current branches/krb5-1-6:krb5-1.6-current branches/krb5-1-7:krb5-1.7-current branches/krb5-1-8:krb5-1.8-current branches/krb5-1-9:krb5-1.9-current branches/krb5-1-10:krb5-1.10-current"
logfile=log
errsto=krbcore@mit.edu
mailto=krb5-snapshot@mit.edu
exec 5>&1 6>&2
exec > $logfile 2>&1

> errors

repos=file:///afs/athena.mit.edu/astaff/project/krbdev/svn/krb5

#/bin/athena/attach -q -n -h gnu outland krbdev svn

#CVS_SERVER=/var/ops/bin/cvs
#export CVS_SERVER

#PATH=/mit/krbdev/bin:/mit/svn/bin:/usr/local/bin:/bin/athena:/usr/athena/bin:/usr/bin:/usr/ccs/bin:/usr/ucb:/bin:/mit/gnu/bin:/mit/outland/bin
#export PATH
PATH=/home/krbsnap/snap/path:$PATH export PATH

#kinit -k -t keytab.daemon daemon/`hostname`
kinit -k -t krbsnap.keytab krbsnap

for i in $taglist; do 
    tag=`echo $i|sed -e 's%:.*%%'`
    dirbase=`echo $i|sed -e 's%.*:%%'`
    olddir=$dirbase.old
    work=$dirbase.work
    updlog=update.$dirbase.log
    upderrs=update.$dirbase.errs
    initlog=init.$dirbase.log
    mkrellog=mkrel.$dirbase.log
    if [ -d $work ]; then :;
    else
	echo "initializing $work..."
	if (mkdir $work && svn checkout $repos/$tag $work) \
	    > $initlog 2>&1; then :;
	else
	    (echo "errors for init of $work"; cat $initlog) >> $errors
	fi
    fi
    echo "executing svn update for $dirbase..."
    if (cd $work && svn update) \
	> $updlog 2> $upderrs; then
	cat $updlog
	if [ -n "`cat $upderrs`" ]; then
	    cat $upderrs
	fi
	if [ -d $olddir ]; then
	    dodiff=t
	else
	    dodiff=nil
	fi
	if grep -s '^Updated' $updlog > /dev/null 2>&1 \
	    || [ "$dodiff" = nil ]; then
	    if [ "$dodiff" = t ]; then
		rm -rf $olddir
	    fi
	    if [ -d $dirbase ]; then mv $dirbase $olddir; fi
	    mkdir $dirbase
	    (cd $work && tar cf - .) | (cd $dirbase && tar xBpf -)
	    echo "running mkrel for $dirbase..."
	    if $work/src/util/mkrel --nocheckout $tag $dirbase \
		> $mkrellog 2>&1; then
		if [ "$dodiff" = t ]; then
		    echo "diffing $dirbase..."
		    diff -urN $olddir $dirbase > $dirbase.diff
		    diff=$dirbase.diff
		else
		    diff=
		fi
		ls -l ${dirbase}*.tar.gz $diff
		scp -p ${dirbase}*.tar.gz $diff \
		    krbsnap@aeneas.mit.edu:/var/ftp/pub/kerberos/dist/vaporware-r-us
		domail=t
	    else
		(echo "mkrel errors for $dirbase!"; cat $mkrellog) >> errors
	    fi
	fi
    else
	(echo "svn update errors for $dirbase!"; \
	    cat $updlog; cat $upderrs) >> errors
    fi
done

kdestroy

echo "done"

exec 1>&5 2>&6

if [ "$domail" = t ]; then
cat - $logfile <<EOF | /usr/lib/sendmail -fkrbcore@mit.edu $mailto
To: $mailto
Subject: snapshot script output

EOF
fi

if [ -n "`cat errors`" ]; then
cat - errors <<EOF | /usr/lib/sendmail -fkrbcore@mit.edu $errsto
To: $errsto
Subject: snapshot errors!

EOF
fi
