#!/bin/sh
domail=nil
taglist="master:krb5-current krb5-1.11:krb5-1.11-current krb5-1.12:krb5-1.12-current krb5-1.13:krb5-1.13-current"
logfile=log
errsto=krbcore@mit.edu
mailto=krb5-snapshot@mit.edu
exec 5>&1 6>&2
exec > $logfile 2>&1

> errors

repos=file:///home/krbsnap/krb5.git
# Share git objects because it's a local repository
shareopt=-s

PATH=/home/krbsnap/snap/path:$PATH export PATH

kinit -k -t krbsnap.keytab krbsnap

for i in $taglist; do 
    tag=`echo $i|sed -e 's%:.*%%'`
    dirbase=`echo $i|sed -e 's%.*:%%'`
    olddir=$dirbase.old
    work=$dirbase.work
    updlog=update.$dirbase.log
    upderrs=update.$dirbase.errs
    initlog=init.$dirbase.log
    mkrellog=mkrel.$dirbase.log
    if [ -d $work ]; then :;
    else
	echo "Initializing $work..."
	if (git clone -q -n $shareopt $repos $work && \
	    cd $work && git reset --hard -q origin/$tag) \
	    > $initlog 2>&1; then :;
	else
	    (echo "errors for init of $work"; cat $initlog) >> $errors
	fi
    fi
    echo "Updating $dirbase..."
    if (cd $work && git fetch -q && \
	git log --pretty=oneline HEAD..origin/$tag) \
	> $updlog 2> $upderrs; then
	cat $updlog
	if [ -n "`cat $upderrs`" ]; then
	    cat $upderrs
	fi
	if [ -d $olddir ]; then
	    dodiff=t
	else
	    dodiff=nil
	fi
	if [ -n "`(cd $work && git rev-list HEAD..origin/$tag)`" ] \
	    || [ "$dodiff" = nil ]; then
	    if [ "$dodiff" = t ]; then
		rm -rf $olddir
		(cd $work && git checkout -q origin/$tag)
	    fi
	    if [ -d $dirbase ]; then mv $dirbase $olddir; fi
	    mkdir $dirbase
	    (cd $work && tar cf - .) | (cd $dirbase && tar xBpf -)
	    echo "running mkrel for $dirbase..."
	    if $work/src/util/mkrel --nocheckout $tag $dirbase \
		> $mkrellog 2>&1; then
		if [ "$dodiff" = t ]; then
		    echo "diffing $dirbase..."
		    diff -urN $olddir $dirbase > $dirbase.diff
		    diff=$dirbase.diff
		else
		    diff=
		fi
		ls -l ${dirbase}*.tar.gz $diff
		scp -p ${dirbase}*.tar.gz $diff \
		    krbsnap@aeneas.mit.edu:/var/ftp/pub/kerberos/dist/vaporware-r-us
		domail=t
	    else
		(echo "mkrel errors for $dirbase!"; cat $mkrellog) >> errors
	    fi
	fi
    else
	(echo "Update errors for $dirbase!"; \
	    cat $updlog; cat $upderrs) >> errors
    fi
done

kdestroy

echo "done"

exec 1>&5 2>&6

if [ "$domail" = t ]; then
cat - $logfile <<EOF | /usr/lib/sendmail -fkrbcore@mit.edu $mailto
To: $mailto
Subject: snapshot script output

EOF
fi

if [ -n "`cat errors`" ]; then
cat - errors <<EOF | /usr/lib/sendmail -fkrbcore@mit.edu $errsto
To: $errsto
Subject: snapshot errors!

EOF
fi
